#!/bin/bash

poetry run black --check . --exclude webex_assistant_sdk/templates
poetry run isort --check
poetry run flake8 --exclude webex_assistant_sdk/templates -- webex_assistant_sdk tests
poetry run pylint -- webex_assistant_sdk tests
