POST http://127.0.0.1:8000/parse
Content-Type: application/json

{
  "challenge": "13fa799f19a260543af1d390e429458319e46bb6918e7b8935ca8e80dafc86c4",
  "text": "sup",
  "context": {},
  "params": {
    "time_zone": "sometime",
    "timestamp": 12345,
    "language": "en"
  },
  "frame": {},
  "history": []
}