# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version:
          - 3.7
        mindmeld-version:
          - 4.3.5rc11
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies (MindMeld ${{ matrix.mindmeld-version }})
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry run pip install mindmeld==${{ matrix.mindmeld-version }}
    - name: Lintme
      run: |
        ./lintme
    - name: Test with pytest
      run: |
        poetry run mindmeld num-parse
        mkdir ~/test-reports
        poetry run pytest --junitxml=~/test-reports/junit.xml --cov-report html --cov=webex_skills
